language: c

os:
        - linux

env:
    - KERNEL_VERSION=3.6.11
    - KERNEL_VERSION=3.16.7
    - KERNEL_VERSION=3.17.3

before_install:
        - sudo apt-get update -qq;

install:
        - sudo apt-get install -y wget
        - ruby tools/ci.kernel.rb $KERNEL_VERSION

before_script:
        - export KDIR=$(cat KDIR)

script:
        - make KDIR=$KDIR

notifications:
    email:
        recipients:
            - yusuke.suzuki@sslab.ics.keio.ac.jp
        on_success: change
        on_failure: always
